remoteWrite:
  - url: http://victoria-logs-cluster-vlinsert.victoria-logs-cluster:9481
    headers:
      VL-Ignore-Fields:
        - kubernetes.container_id
        - kubernetes.pod_ip
        - kubernetes.pod_labels.pod-template-hash
collector:
  msgField:
    - message
    - msg
    # - http.uri
