remoteWrite:
  - url: http://vlc-victoria-logs-cluster-vlinsert.victorialogs:9481
    headers:
      VL-Ignore-Fields:
        - kubernetes.container_id
        - kubernetes.pod_ip
        - kubernetes.pod_name
collector:
  msgField:
    - message
    - msg
    - http.uri
